/**
 * Voiceover Configuration for Vibrant Intelligence Product Video
 *
 * Maps each voiceover line to its audio file, scene, and timing.
 * Audio files are generated by ElevenLabs TTS and stored in src/assets/audio/
 *
 * File naming: scene-{sceneId}-{feature}-{lineIndex}.wav
 */

// Import all voiceover audio files
import intro_0 from "../assets/audio/scene-00-intro-0.wav";
import intro_1 from "../assets/audio/scene-00-intro-1.wav";
import intro_2 from "../assets/audio/scene-00-intro-2.wav";

import feature1_0 from "../assets/audio/scene-01-chat-0.wav";
import feature1_1 from "../assets/audio/scene-01-chat-1.wav";
import feature1_2 from "../assets/audio/scene-01-chat-2.wav";
import feature1_3 from "../assets/audio/scene-01-chat-3.wav";

import feature2_0 from "../assets/audio/scene-02-health-0.wav";
import feature2_1 from "../assets/audio/scene-02-health-1.wav";
import feature2_2 from "../assets/audio/scene-02-health-2.wav";

import feature3_0 from "../assets/audio/scene-03-calendar-0.wav";
import feature3_1 from "../assets/audio/scene-03-calendar-1.wav";
import feature3_2 from "../assets/audio/scene-03-calendar-2.wav";
import feature3_3 from "../assets/audio/scene-03-calendar-3.wav";
import feature3_4 from "../assets/audio/scene-03-calendar-4.wav";

import feature4_0 from "../assets/audio/scene-04-pegboard-0.wav";
import feature4_1 from "../assets/audio/scene-04-pegboard-1.wav";
import feature4_2 from "../assets/audio/scene-04-pegboard-2.wav";

import feature5_0 from "../assets/audio/scene-05-quickactions-0.wav";
import feature5_1 from "../assets/audio/scene-05-quickactions-1.wav";
import feature5_2 from "../assets/audio/scene-05-quickactions-2.wav";
import feature5_3 from "../assets/audio/scene-05-quickactions-3.wav";

import feature6_0 from "../assets/audio/scene-06-notes-0.wav";
import feature6_1 from "../assets/audio/scene-06-notes-1.wav";
import feature6_2 from "../assets/audio/scene-06-notes-2.wav";
import feature6_3 from "../assets/audio/scene-06-notes-3.wav";
import feature6_4 from "../assets/audio/scene-06-notes-4.wav";

import feature7_0 from "../assets/audio/scene-07-workflows-0.wav";
import feature7_1 from "../assets/audio/scene-07-workflows-1.wav";
import feature7_2 from "../assets/audio/scene-07-workflows-2.wav";
import feature7_3 from "../assets/audio/scene-07-workflows-3.wav";
import feature7_4 from "../assets/audio/scene-07-workflows-4.wav";
import feature7_5 from "../assets/audio/scene-07-workflows-5.wav";
import feature7_6 from "../assets/audio/scene-07-workflows-6.wav";

import feature8_0 from "../assets/audio/scene-08-forms-0.wav";
import feature8_1 from "../assets/audio/scene-08-forms-1.wav";
import feature8_2 from "../assets/audio/scene-08-forms-2.wav";
import feature8_3 from "../assets/audio/scene-08-forms-3.wav";
import feature8_4 from "../assets/audio/scene-08-forms-4.wav";

import feature9_0 from "../assets/audio/scene-09-practice-0.wav";
import feature9_1 from "../assets/audio/scene-09-practice-1.wav";
import feature9_2 from "../assets/audio/scene-09-practice-2.wav";
import feature9_3 from "../assets/audio/scene-09-practice-3.wav";
import feature9_4 from "../assets/audio/scene-09-practice-4.wav";

import transition1 from "../assets/audio/scene-10-transition-onemorething-0.wav";

import feature10_0 from "../assets/audio/scene-10-collaborate-0.wav";

import feature11_0 from "../assets/audio/scene-11-sign-0.wav";

import feature12_0 from "../assets/audio/scene-12-approve-0.wav";
import feature12_1 from "../assets/audio/scene-12-approve-1.wav";

import transition2 from "../assets/audio/scene-13-transition-comingsoon-0.wav";

import feature13_0 from "../assets/audio/scene-13-composer-0.wav";
import feature13_1 from "../assets/audio/scene-13-composer-1.wav";
import feature13_2 from "../assets/audio/scene-13-composer-2.wav";
import feature13_3 from "../assets/audio/scene-13-composer-3.wav";
import feature13_4 from "../assets/audio/scene-13-composer-4.wav";
import feature13_5 from "../assets/audio/scene-13-composer-5.wav";
import feature13_6 from "../assets/audio/scene-13-composer-6.wav";

import outro0 from "../assets/audio/scene-14-outro-0.wav";
import outro1 from "../assets/audio/scene-14-outro-1.wav";

/**
 * Voiceover Line Interface
 * Each line has an audio file, the text spoken, and timing information
 */
export interface VoiceoverLine {
  id: string;
  audio: string;
  text: string;
  // Start time in frames (30fps) relative to scene start
  startFrame?: number;
}

/**
 * Scene Voiceover Configuration
 * Groups voiceover lines by scene with their starting positions
 */
export interface SceneVoiceover {
  sceneId: string;
  sceneName: string;
  lines: VoiceoverLine[];
}

/**
 * Complete voiceover timeline configuration
 * Lines are sequenced to play one after another within each scene
 * Timings are approximate and may need adjustment based on actual audio duration
 */
export const VOICEOVER_CONFIG: SceneVoiceover[] = [
  // INTRO - Logo animation + Dashboard flash (450 frames = 15s)
  // Voiceover starts when dashboard appears at frame 160
  {
    sceneId: "intro",
    sceneName: "INTRO",
    lines: [
      { id: "intro-0", audio: intro_0, text: "Running a modern practice means juggling patient care, communication, scheduling, and documentation—all at once.", startFrame: 180 },
      { id: "intro-1", audio: intro_1, text: "What if your EHR actually helped instead of getting in the way?", startFrame: 0 }, // Will be calculated sequentially
      { id: "intro-2", audio: intro_2, text: "Meet Vibrant Intelligence: an AI-powered platform built for how clinics actually work.", startFrame: 0 }, // Will be calculated sequentially
    ],
  },

  // Feature 1: Chat + SMS + Email
  {
    sceneId: "feature1",
    sceneName: "Chat + SMS + Email",
    lines: [
      { id: "feature1-0", audio: feature1_0, text: "First up: unified communication.", startFrame: 10 }, // Small delay after scene starts
      { id: "feature1-1", audio: feature1_1, text: "Text messages, emails, and chat—all in one interface.", startFrame: 0 }, // Calculated sequentially
      { id: "feature1-2", audio: feature1_2, text: "No more switching between apps.", startFrame: 0 }, // Calculated sequentially
      { id: "feature1-3", audio: feature1_3, text: "Every interaction with a patient lives in one place, so your team always has the full picture.", startFrame: 0 }, // Calculated sequentially
    ],
  },

  // FEATURE 2: Health Tab (0:25-0:37, 360 frames)
  {
    sceneId: "feature2",
    sceneName: "Health Tab",
    lines: [
      { id: "feature2-0", audio: feature2_0, text: "Click the Health tab to instantly access everything about this patient: medications, allergies, vitals, labs, encounter notes, and uploaded documents.", startFrame: 30 },
      { id: "feature2-1", audio: feature2_1, text: "Dynamic variables pull data directly from your records—no hunting through multiple screens.", startFrame: 180 },
      { id: "feature2-2", audio: feature2_2, text: "Tag important items, track program progress, and keep clinical context at your fingertips.", startFrame: 270 },
    ],
  },

  // FEATURE 3: Calendar (0:37-0:49, 360 frames)
  {
    sceneId: "feature3",
    sceneName: "Calendar",
    lines: [
      { id: "feature3-0", audio: feature3_0, text: "The Calendar gives your team a complete scheduling dashboard.", startFrame: 20 },
      { id: "feature3-1", audio: feature3_1, text: "Color-coded appointments across all providers, so everyone knows what's happening at a glance.", startFrame: 70 },
      { id: "feature3-2", audio: feature3_2, text: "For patients, we offer a self-scheduling link—like Calendly, but built right in.", startFrame: 160 },
      { id: "feature3-3", audio: feature3_3, text: "Plus, seamless integration with Google Calendar, Outlook, and Zoom.", startFrame: 230 },
      { id: "feature3-4", audio: feature3_4, text: "Appointments sync automatically, and virtual visits launch with one click.", startFrame: 290 },
    ],
  },

  // FEATURE 4: Peg Board (0:49-0:57, 240 frames)
  {
    sceneId: "feature4",
    sceneName: "Peg Board",
    lines: [
      { id: "feature4-0", audio: feature4_0, text: "See this panel on the right? That's the Peg Board.", startFrame: 30 },
      { id: "feature4-1", audio: feature4_1, text: "Pin any important item—a lab result, a note, an upcoming appointment—right here for quick reference.", startFrame: 80 },
      { id: "feature4-2", audio: feature4_2, text: "Think of it as your personal sticky note wall for each patient.", startFrame: 170 },
    ],
  },

  // FEATURE 5: Quick Actions (0:57-1:07, 300 frames)
  {
    sceneId: "feature5",
    sceneName: "Quick Actions",
    lines: [
      { id: "feature5-0", audio: feature5_0, text: "Right above the message input, you'll find Quick Actions.", startFrame: 20 },
      { id: "feature5-1", audio: feature5_1, text: "One click to create an order, schedule an appointment, send documents, assign a workflow, or start an encounter note.", startFrame: 70 },
      { id: "feature5-2", audio: feature5_2, text: "Everything happens in context—no navigating away, no lost time.", startFrame: 190 },
      { id: "feature5-3", audio: feature5_3, text: "You stay focused on the patient.", startFrame: 250 },
    ],
  },

  // FEATURE 6: Encounter Notes (1:07-1:32, 750 frames)
  {
    sceneId: "feature6",
    sceneName: "Encounter Notes",
    lines: [
      { id: "feature6-0", audio: feature6_0, text: "Encounter Notes are where Vibrant Intelligence really shines.", startFrame: 40 },
      { id: "feature6-1", audio: feature6_1, text: "Had a Zoom call with your patient? The platform captures the conversation and generates a summary—ready to insert directly into your note.", startFrame: 110 },
      { id: "feature6-2", audio: feature6_2, text: "Insert action cards to order labs, schedule follow-ups, or prescribe—all without leaving the note.", startFrame: 350 },
      { id: "feature6-3", audio: feature6_3, text: "Use smart blocks and templates that auto-populate with patient data.", startFrame: 520 },
      { id: "feature6-4", audio: feature6_4, text: "Documentation that actually helps you work—not slow you down.", startFrame: 640 },
    ],
  },

  // FEATURE 7: Workflow + AI (1:32-2:02, 900 frames)
  {
    sceneId: "feature7",
    sceneName: "Workflow + AI",
    lines: [
      { id: "feature7-0", audio: feature7_0, text: "Now let's talk about Workflows—one of the most powerful features in the platform.", startFrame: 30 },
      { id: "feature7-1", audio: feature7_1, text: "Build custom care pathways using pre-built component nodes: send a message, wait for a response, schedule an appointment, check a condition, and more.", startFrame: 110 },
      { id: "feature7-2", audio: feature7_2, text: "Configure each step to match exactly how your practice operates.", startFrame: 380 },
      { id: "feature7-3", audio: feature7_3, text: "But here's where it gets exciting—just describe what you need in plain English, and our AI builds the workflow for you.", startFrame: 480 },
      { id: "feature7-4", audio: feature7_4, text: "Once a patient is enrolled, Guardian AI monitors their progress.", startFrame: 670 },
      { id: "feature7-5", audio: feature7_5, text: "It handles routine exceptions automatically—and when human judgment is needed, it brings you into the loop.", startFrame: 760 },
      { id: "feature7-6", audio: feature7_6, text: "Automation with oversight.", startFrame: 860 },
    ],
  },

  // FEATURE 8: Form Builder (2:02-2:22, 600 frames)
  {
    sceneId: "feature8",
    sceneName: "Form Builder",
    lines: [
      { id: "feature8-0", audio: feature8_0, text: "Need an intake form? A questionnaire? A waiver?", startFrame: 30 },
      { id: "feature8-1", audio: feature8_1, text: "The Form Builder has you covered.", startFrame: 90 },
      { id: "feature8-2", audio: feature8_2, text: "Drag and drop pre-built components, or describe what you need and let AI build it for you.", startFrame: 140 },
      { id: "feature8-3", audio: feature8_3, text: "Here's the best part: map form fields to patient records, and when patients fill something out, that data flows directly into their chart.", startFrame: 330 },
      { id: "feature8-4", audio: feature8_4, text: "No manual entry, no copy-paste errors.", startFrame: 500 },
    ],
  },

  // FEATURE 9: My Practice (2:22-2:40, 540 frames)
  {
    sceneId: "feature9",
    sceneName: "My Practice",
    lines: [
      { id: "feature9-0", audio: feature9_0, text: "My Practice is your command center.", startFrame: 30 },
      { id: "feature9-1", audio: feature9_1, text: "Customizable metrics let you track what matters most to your clinic.", startFrame: 90 },
      { id: "feature9-2", audio: feature9_2, text: "Our sentiment analysis scans patient communications to surface potential issues before they escalate—helping you improve satisfaction and catch concerns early.", startFrame: 200 },
      { id: "feature9-3", audio: feature9_3, text: "And if you have a question about your data? Just ask.", startFrame: 420 },
      { id: "feature9-4", audio: feature9_4, text: 'Type a natural language query like "Show me no-show rates for the past month"—and get your answer instantly.', startFrame: 460 },
    ],
  },

  // TRANSITION: One More Thing (2:40-2:43, 90 frames)
  {
    sceneId: "transition1",
    sceneName: "One More Thing",
    lines: [
      { id: "transition1-0", audio: transition1, text: "We've shown you a lot. But we've saved the best for last.", startFrame: 10 },
    ],
  },

  // FEATURE 10: Collaborate (2:43-2:48, 150 frames)
  {
    sceneId: "feature10",
    sceneName: "Real-time Collaboration",
    lines: [
      { id: "feature10-0", audio: feature10_0, text: "See your team working live in the chart—multiple providers, all in sync.", startFrame: 10 },
    ],
  },

  // FEATURE 11: Sign (2:48-2:53, 150 frames)
  {
    sceneId: "feature11",
    sceneName: "Sign Anywhere",
    lines: [
      { id: "feature11-0", audio: feature11_0, text: "Sign notes with your finger. One tap, and it's finalized.", startFrame: 10 },
    ],
  },

  // FEATURE 12: Approve (2:53-2:58, 150 frames)
  {
    sceneId: "feature12",
    sceneName: "Approval Center",
    lines: [
      { id: "feature12-0", audio: feature12_0, text: "Review all pending changes in one place.", startFrame: 10 },
      { id: "feature12-1", audio: feature12_1, text: "Approve, reject, or edit—you're always in control.", startFrame: 60 },
    ],
  },

  // TRANSITION: Coming Soon (2:58-3:01, 90 frames)
  {
    sceneId: "transition2",
    sceneName: "Coming Soon",
    lines: [
      { id: "transition2-0", audio: transition2, text: "Coming soon.", startFrame: 20 },
    ],
  },

  // FEATURE 13: Composer (3:01-3:18, 510 frames)
  {
    sceneId: "feature13",
    sceneName: "Composer",
    lines: [
      { id: "feature13-0", audio: feature13_0, text: "Introducing Composer—your AI-powered command center for Vibrant Intelligence.", startFrame: 30 },
      { id: "feature13-1", audio: feature13_1, text: "Composer understands natural language and turns it into action.", startFrame: 120 },
      { id: "feature13-2", audio: feature13_2, text: "Need to write a note? Just describe the visit.", startFrame: 210 },
      { id: "feature13-3", audio: feature13_3, text: "Need to send a follow-up? Tell Composer what to say.", startFrame: 280 },
      { id: "feature13-4", audio: feature13_4, text: "Review changes with a clear diff view—accept, modify, or reject.", startFrame: 360 },
      { id: "feature13-5", audio: feature13_5, text: "Generate documents, update records, manage schedules—all through conversation.", startFrame: 430 },
      { id: "feature13-6", audio: feature13_6, text: "Composer is the future of practice management.", startFrame: 460 },
    ],
  },

  // STACKED CARDS: "One Platform, Everything You Need" (4:18-4:23, 150 frames)
  {
    sceneId: "stackedCards",
    sceneName: "Stacked Cards",
    lines: [
      { id: "outro-0", audio: outro0, text: "That's Vibrant Intelligence.", startFrame: 20 },
      { id: "outro-1", audio: outro1, text: "Everything you need.", startFrame: 60 },
    ],
  },

  // OUTRO (4:23-4:39, 480 frames) - Logo only, no voiceover
  {
    sceneId: "outro",
    sceneName: "OUTRO",
    lines: [],
  },
];

/**
 * Helper function to get voiceover lines for a specific scene
 */
export function getVoiceoverForScene(sceneId: string): SceneVoiceover | undefined {
  return VOICEOVER_CONFIG.find((scene) => scene.sceneId === sceneId);
}

/**
 * Get all voiceover audio files as a flat array with their global timeline positions
 * Returns { audio, startFrame, durationInFrames } for each line
 *
 * IMPORTANT: Each audio element is wrapped in a Sequence with a specific duration
 * to prevent overlap - audio only plays during its designated time window
 *
 * Voiceovers are now sequenced consecutively within each scene to prevent overlap
 */
export function getAllVoiceoverTracks(): Array<{ audio: string; startFrame: number; durationInFrames: number }> {
  const tracks: Array<{ audio: string; startFrame: number; durationInFrames: number }> = [];

  // Scene start frames - extended intro (630 frames = 21s)
  const sceneStartFrames: Record<string, number> = {
    intro: 0,          // 0:00 (630 frames - extended for voiceover)
    feature1: 630,     // 0:21 (420 frames)
    feature2: 1050,    // 0:35 (660 frames)
    feature3: 1710,    // 0:57 (660 frames)
    feature4: 2370,    // 1:19 (400 frames)
    feature5: 2770,    // 1:32 (500 frames)
    feature6: 3270,    // 1:49 (750 frames)
    feature7: 4020,    // 2:14 (1110 frames)
    feature8: 5130,    // 2:51 (620 frames)
    feature9: 5750,    // 3:11 (740 frames)
    transition1: 6490, // 3:36 (120 frames)
    feature10: 6610,   // 3:40 (150 frames)
    feature11: 6760,   // 3:45 (150 frames)
    feature12: 6910,   // 3:50 (180 frames)
    transition2: 7090, // 3:56 (60 frames)
    feature13: 7150,   // 3:58 (780 frames)
    stackedCards: 7930, // 4:24 (110 frames) - "One Platform, Everything You Need"
    outro: 8040,        // 4:28 (240 frames, 8s) - Logo only, no voiceover
  };

  // Actual durations for each voiceover line (in frames at 30fps)
  // Measured from generated audio files
  const estimatedDurations: Record<string, number> = {
    // INTRO voiceovers
    "intro-0": 197,    // 6.56s
    "intro-1": 92,     // 3.08s
    "intro-2": 154,    // 5.12s
    "feature1-0": 69,   // 2.30s
    "feature1-1": 101,   // 3.37s
    "feature1-2": 58,   // 1.93s
    "feature1-3": 146,   // 4.86s
    "feature2-0": 318,   // 10.61s
    "feature2-1": 168,   // 5.59s
    "feature2-2": 152,   // 5.07s
    "feature3-0": 96,   // 3.19s
    "feature3-1": 140,   // 4.65s
    "feature3-2": 136,   // 4.52s
    "feature3-3": 130,   // 4.34s
    "feature3-4": 134,   // 4.47s
    "feature4-0": 82,   // 2.72s
    "feature4-1": 204,   // 6.79s
    "feature4-2": 94,   // 3.13s
    "feature5-0": 96,   // 3.21s
    "feature5-1": 193,   // 6.43s
    "feature5-2": 127,   // 4.23s
    "feature5-3": 60,   // 2.01s
    "feature6-0": 96,   // 3.21s
    "feature6-1": 250,   // 8.33s
    "feature6-2": 162,   // 5.41s
    "feature6-3": 109,   // 3.63s
    "feature6-4": 100,   // 3.32s
    "feature7-0": 132,   // 4.39s
    "feature7-1": 265,   // 8.83s
    "feature7-2": 112,   // 3.74s
    "feature7-3": 179,   // 5.96s
    "feature7-4": 118,   // 3.92s
    "feature7-5": 182,   // 6.06s
    "feature7-6": 49,   // 1.65s
    "feature8-0": 87,   // 2.90s
    "feature8-1": 56,   // 1.88s
    "feature8-2": 139,   // 4.62s
    "feature8-3": 243,   // 8.10s
    "feature8-4": 71,   // 2.35s
    "feature9-0": 62,   // 2.06s
    "feature9-1": 107,   // 3.55s
    "feature9-2": 274,   // 9.12s
    "feature9-3": 87,   // 2.90s
    "feature9-4": 190,   // 6.32s
    "transition1-0": 96,   // 3.21s
    "feature10-0": 126,   // 4.21s
    "feature11-0": 96,   // 3.19s
    "feature12-0": 66,   // 2.19s
    "feature12-1": 89,   // 2.95s
    "transition2-0": 30,   // 0.99s
    "feature13-0": 146,   // 4.86s
    "feature13-1": 112,   // 3.74s
    "feature13-2": 74,   // 2.48s
    "feature13-3": 85,   // 2.85s
    "feature13-4": 132,   // 4.39s
    "feature13-5": 137,   // 4.57s
    "feature13-6": 78,   // 2.61s
    "outro-0": 50,   // 1.67s - "That's Vibrant Intelligence."
    "outro-1": 38,   // 1.28s - "Everything you need."
  };

  // Calculate voiceover positions sequentially within each scene
  // This ensures no overlap - each voiceover starts after the previous one finishes
  for (const scene of VOICEOVER_CONFIG) {
    const sceneStart = sceneStartFrames[scene.sceneId] ?? 0;
    let voiceoverOffset = scene.lines[0]?.startFrame ?? 0; // Start from first line's offset

    for (const line of scene.lines) {
      const lineStart = sceneStart + voiceoverOffset;
      const duration = estimatedDurations[line.id] ?? 90;
      tracks.push({ audio: line.audio, startFrame: lineStart, durationInFrames: duration });

      // Move offset forward for next voiceover line
      voiceoverOffset += duration;
    }
  }

  return tracks;
}

/**
 * Export the new scene start frames for use in Video.tsx
 */
export const SCENE_START_FRAMES: Record<string, number> = {
  intro: 0,          // 0:00 (630 frames - extended for voiceover)
  feature1: 630,     // 0:21 (420 frames)
  feature2: 1050,    // 0:35 (660 frames)
  feature3: 1710,    // 0:57 (660 frames)
  feature4: 2370,    // 1:19 (400 frames)
  feature5: 2770,    // 1:32 (500 frames)
  feature6: 3270,    // 1:49 (750 frames)
  feature7: 4020,    // 2:14 (1110 frames)
  feature8: 5130,    // 2:51 (620 frames)
  feature9: 5750,    // 3:11 (740 frames)
  transition1: 6490, // 3:36 (120 frames)
  feature10: 6610,   // 3:40 (150 frames)
  feature11: 6760,   // 3:45 (150 frames)
  feature12: 6910,   // 3:50 (180 frames)
  transition2: 7090, // 3:56 (60 frames)
  feature13: 7150,   // 3:58 (780 frames)
  stackedCards: 7930, // 4:24 (110 frames) - "One Platform, Everything You Need" with voiceover
  outro: 8040,        // 4:28 (240 frames, 8s) - Logo only, no voiceover
};

/**
 * Export the new scene durations for use in Video.tsx
 */
export const SCENE_DURATIONS: Record<string, number> = {
  intro: 630,        // 21s - extended for voiceover completion
  feature1: 420,     // 14s
  feature2: 660,     // 22s
  feature3: 660,     // 22s
  feature4: 400,     // 13.3s
  feature5: 500,     // 16.7s
  feature6: 750,     // 25s
  feature7: 1110,    // 37s
  feature8: 620,     // 20.7s
  feature9: 740,     // 24.7s
  transition1: 120,  // 4s
  feature10: 150,    // 5s
  feature11: 150,    // 5s
  feature12: 180,    // 6s
  transition2: 60,   // 2s
  feature13: 780,    // 26s
  outro: 240,        // 8s
};

/**
 * Total video duration in frames
 */
export const TOTAL_VIDEO_FRAMES = 8280; // ~4:36 at 30fps
